### ISSUE TITLE
Jellyfin 10.7.7 the plugin is not displayed for installation

### ISSUE THREAD

**Issue by Pascal51882** [jellyfin/jellyfin-plugin-simkl#14]
I am using Jellyfin 10.7.7 the plugin is not displayed for installation.
I already use the repo for another plugin.
What could be the problem?

**Comment by crobibero** [comment]
The plugin is not available for 10.7

**Comment by Pascal51882** [comment]
The guide says 10.7 https://simkl.com/apps/jellyfin/
