### ISSUE TITLE
V6 not published on the official catalogue

### ISSUE THREAD

**Issue by JamsRepos** [jellyfin/jellyfin-plugin-simkl#36]
Hey!

I see the release was out yesterday, thanks for this. Although, me and a few others cannot upgrade as <https://repo.jellyfin.org/releases/plugin/simkl/simkl_6.0.0.0.zip> is a dead link as well as on the Jellyfin Catalogue only version 5 is available. A lot of people's servers are crashing with V5 until they upgrade, which isn't possible so a complete plugin deletion is required.

Thanks!

**Comment by crobibero** [comment]
Thanks for the issue- the publish workflow failed so the manifest was never actually updated!
v6 is now available
