### ISSUE TITLE
Repo - Clodflare Error - Edge IP Restricted

### ISSUE THREAD

**Issue by marvin8** [jellyfin/jellyfin-plugin-simkl#7]
Trying to load your repo I get a cloudflare error as below:

```

Please enable cookies.
Error 1034
Ray ID: 6d5dc3bebff454fd • 2022-01-30 21:24:00 UTC
Edge IP Restricted
What happened?

You've requested a page on a website that is part of the Cloudflare network. The host (repo.codyrobibero.dev) resolved to an IP address that the owner of the website does not have access to.
What can I do?

If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS records to ensure they are pointed to the IP address(es) you were assigned at registration.

Cloudflare Ray ID: 6d5dc3bebff454fd • Your IP: [...redacted...] • Performance & security by Cloudflare

```

Is there anything I can do on my end to get your repo to load for me?

**Comment by crobibero** [comment]
Sorry, my repo went down hard. I've moved this plugin to the Jellyfin organization,  so next release will be from the main manifest.

If I have time today I'll manually create a release on the repo here

**Comment by marvin8** [comment]
A new release to the Jellyfin repo would be awesome... thank you :)

**Comment by crobibero** [comment]
The plugin (v2, for Jellyfin 10.8-beta.1) is now available in the official Jellyfin repo
