### ISSUE TITLE
Jellyfin Simkl

### ISSUE THREAD

**Issue by 31bado** [jellyfin/jellyfin-plugin-simkl#8]
Simkl not showing on Catalog after following the instuctions at:

https://simkl.com/apps/jellyfin/connected/

Using Jellyfin 10.7

Thanks.

**Comment by crobibero** [comment]
Hi,

My repo server died, and wont be coming back. After 10.8 is released I will publish this plugin to the official Jellyfin plugin repo.

**Comment by 31bado** [comment]
Thanks for your answer.

**Comment by crobibero** [comment]
The plugin (v2, for Jellyfin 10.8-beta.1) is now available in the official Jellyfin repo
