### ISSUE TITLE
Built the plugin but error logging in

### ISSUE THREAD

**Issue by Fallenbagel** [jellyfin/jellyfin-plugin-simkl#9]
I built the plugin from the source code with no issues and it runs on jellyfin, however, when i try to log in i get the pop up error logging in.
Here's what it says in the logs.
`[06:50:43] [DBG] [8] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.`

**Comment by JodliDev** [comment]
Logging in with Jellyfin 10.8.0 and plugin-version 2.0 seems to be broken.
I am getting the same error when installing it from the official repositories :/

**Comment by Yveske82** [comment]
> Logging in with Jellyfin 10.8.0 and plugin-version 2.0 seems to be broken. I am getting the same error when installing it from the official repositories :/

Jellyfin 10.8.0 stable release yesterday but the plugin still won't work.

**Comment by crobibero** [comment]
I've fixed the basics in #17, but the config page is still pretty rough
